[tool.ruff]
line-length = 79
select = [
    "E",
    "W",
    "F",
    "C90",
    "B",
    "S",
    "I",
    "D",
    "N",
    "Q",
    "T",
]

ignore = [
    "D100",
]
exclude = [".venv/*", "migrations", "__pycache__"]

