from .student import Student
from .teacher import Teacher
from .course import Course
from .course_instance import CourseInstance
from .course_section import CourseSection
from .course_prerequisite import CoursePrerequisite
from .evaluation_type import EvaluationType
from .evaluation import Evaluation
from .student_evaluation import StudentEvaluations
from .student_course import StudentCourses
from .classroom import Classroom
from .schedule import Schedule 
from .timeslot import TimeSlot
